--- #YAML:1.0
name:                Email-Delete
version:             2.001
abstract:            Delete Messages from Folders
license:             perl
author:              
    - Casey West <casey@geeknest.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Email::Folder:                 0.84
    Email::FolderType:             0.7
    Email::LocalDelivery:          0.213
    Email::Simple:                 1.92
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
